# Generated by Django 5.2.9 on 2026-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientdevice',
            table='norm_client_devices',
        ),
        migrations.AlterModelTable(
            name='clientsession',
            table='norm_client_sessions',
        ),
        migrations.AlterModelTable(
            name='partnerdevice',
            table='norm_partner_devices',
        ),
        migrations.AlterModelTable(
            name='partnersession',
            table='norm_partner_sessions',
        ),
    ]
