# Generated by Django 5.2.12 on 2026-03-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20260324_0033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partnerdevice',
            table='norm_partner_devices',
        ),
    ]
