# Generated by Django 5.2.9 on 2026-03-13 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('notification_type', models.CharField(choices=[('booking_new', 'New Booking'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('booking_no_show', 'Booking No Show'), ('system', 'System'), ('promo', 'Promotion')], default='system', max_length=30, verbose_name='Notification Type')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data like booking_id, etc.', verbose_name='Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Partner Notification',
                'verbose_name_plural': 'Partner Notifications',
                'db_table': 'partner_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
