# Generated by Django 5.2.9 on 2026-02-19 12:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM payment_exchangerate WHERE deleted_at IS NOT NULL;
            DELETE FROM payment_plumtransaction WHERE deleted_at IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='plumtransaction',
            name='deleted_at',
        ),
    ]
